### PR TITLE
Add mac specific install, setup instructions and basic doc update

### PR DESCRIPTION
**Pull request by souvikhaldar**

### CODE REVIEW

**Review by trycatcher — CHANGES_REQUESTED** [review]
@souvikhaldar 

If we're adding OS-specific instructions, let's have nested them inside `Setup` without interleaving. That way `Setup` stays OS-agnostic and you don't have to prefix every change with `install on Mac`

The Emacs setup could be shorter if you clone the source repo, move it to $HOME as .emacs.d

Lastly, `Read Online` should be a separate commit

**Comment by souvikhaldar** [comment]
> The Emacs setup could be shorter if you clone the source repo, move it to $HOME as .emacs.d

Sometimes `.emacs.d` is already populated so you would want to move specific files to the already present `.emacs.d` (hence `-p` flag). Do you want to move `*` of the repo to `.emacs.d` instead of just `init.el`?

**Comment by trycatcher** [comment]
@souvikhaldar This setup assumes that there is no previous Emacs configuration so we want to start off with our `.emacs.d`. An `.emacs.d` might exist from before since that gets created when you open Emacs. So i'll recommend these ordered steps for the Mac-specific setup
1. `rm -rf $HOME/.emacs.d`
2. `git clone  beginning-clojure-emacs.d`
3. `mv beginning-clojure-emacs.d $HOME/emacs.d`

If there is a previous Emacs configuration by an experienced Emacs user we can assume they'll be able to adapt our configuration to their needs.

**Comment by trycatcher** [comment]
Also the last step `Setup Emacs with https://github.com/koljure/beginning-clojure-emacs.d` seems to have got removed from the `General` setup. Could you please add it back? We want to have this around for general setup and detail it for OS-specific ones.

**Comment by souvikhaldar** [comment]
> 1. rm -rf $HOME/.emacs.d

After `rm` we need to create `emacs.d` then do `mv` step.

**Comment by trycatcher** [comment]
@souvikhaldar The directory creation is not necessary. `mv` itself will create the directory if the target doesn't exist. If you create the target directory first `mv` will create the source _inside_ the target directory.

**Pull request closed without merging**
